[build]
builder = "NIXPACKS"

[deploy]
startCommand = "php -S 0.0.0.0:${PORT:-8080}"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"

[phases.setup]
nixPkgs = ["php81"]

[phases.build]
cmds = [
    "mkdir -p /app",
    "cp -r . /app"
] 