[build]
builder = "DOCKERFILE"
dockerfilePath = "tp10/Dockerfile"

[deploy]
healthcheckPath = "/tp10"
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[phases.setup]
nixPkgs = ["php81"]

[phases.build]
cmds = [
    "mkdir -p /app",
    "cp -r . /app"
] 